"""Small S3 helpers for the FastAPI backend.

The backend should rely on the default boto3 credential chain. On EC2, that
means an attached IAM role can grant S3 access without putting AWS keys in code.
"""

from __future__ import annotations

import io
import os
import pickle
from typing import Any

import boto3
import pandas as pd


def _s3_client():
    region = os.getenv("AWS_REGION", "us-east-2")
    return boto3.client("s3", region_name=region)


def s3_bucket() -> str:
    bucket = os.getenv("S3_BUCKET")
    if not bucket:
        raise RuntimeError("S3_BUCKET is required when reading from S3.")
    return bucket


def read_bytes_from_s3(key: str) -> bytes:
    obj = _s3_client().get_object(Bucket=s3_bucket(), Key=key)
    return obj["Body"].read()


def read_csv_from_s3(key: str) -> pd.DataFrame:
    return pd.read_csv(io.BytesIO(read_bytes_from_s3(key)))


def read_pickle_from_s3(key: str) -> Any:
    # Only load pickle artifacts generated by the team.
    return pickle.loads(read_bytes_from_s3(key))
